app = "medical-rag-chatbot"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory_mb = 2048
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8001"

