services:
  - type: web
    name: medical-chatbot
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: docker build -t medical-chatbot .
    startCommand: docker run -p $PORT:$PORT -e PORT=$PORT medical-chatbot
    envVars:
      - key: PORT
        generateValue: true

