services:
  - type: web
    name: medical-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # You'll need to add this in Render dashboard

